# Generated by Django 4.0.6 on 2022-07-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
    ]
