# Generated by Django 4.0.6 on 2022-07-28 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_articles_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-date', 'title'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AddField(
            model_name='articles',
            name='upload_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='files_articles/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
