# Generated by Django 4.0.6 on 2022-07-31 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docs', '0006_alter_articles_options_articles_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='upload_file',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d/', verbose_name='Файл на загрузку'),
        ),
        migrations.CreateModel(
            name='Informed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_informed', models.BooleanField(default=False, verbose_name='Ознакомлен')),
                ('date_informed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата ознакомления')),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='docs.articles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_informed', to=settings.AUTH_USER_MODEL)),
                ('users_informed', models.ManyToManyField(blank=True, related_name='title_informed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ознакомлен(а)',
                'verbose_name_plural': 'Ознакомлены',
            },
        ),
    ]
